title: Cybersecurity for Beginners
description: Plain-English guides on compliance and security
theme: jekyll-theme-minimal

author: Nilson Marques
url: https://nilson-marques.github.io
baseurl: /cybertip
show_downloads: false
